In [41]:
import pandas as pd

In [9]:
df = pd.read_csv("Ecommerce_Consumer_Behavior_Analysis_Data.csv")

In [8]:
df2 = df.copy() #kopyalama işlemi

In [35]:
df.drop(columns=['Engagement_with_Ads']) #df'den yazılı sütunu silme işlemi

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Return_Rate,Customer_Satisfaction,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
0,37-611-6911,22,Female,Middle,Married,Bachelor's,Middle,Évry,Gardening & Outdoors,$333.80,...,1,7,Tablet,Credit Card,3/1/2024,True,False,Need-based,No Preference,2
1,29-392-9296,49,Male,High,Married,High School,High,Huocheng,Food & Beverages,$222.22,...,1,5,Tablet,PayPal,4/16/2024,True,False,Wants-based,Standard,6
2,84-649-5117,24,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,$426.22,...,1,7,Smartphone,Debit Card,3/15/2024,True,True,Impulsive,No Preference,3
3,48-980-6078,29,Female,Middle,Single,Master's,Middle,Wiwilí,Home Appliances,$101.31,...,0,1,Smartphone,Other,10/4/2024,True,True,Need-based,Express,10
4,91-170-9072,33,Female,Middle,Widowed,High School,Middle,Nara,Furniture,$211.70,...,2,10,Smartphone,Debit Card,1/30/2024,False,False,Wants-based,No Preference,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,20-562-2569,44,Female,High,Divorced,Bachelor's,High,Aramayuan,Mobile Accessories,$463.67,...,2,4,Tablet,PayPal,7/7/2024,True,False,Need-based,Standard,5
996,41-366-4205,50,Female,High,Single,High School,Middle,Paquera,Gardening & Outdoors,$69.78,...,0,6,Tablet,Cash,3/28/2024,True,False,Wants-based,No Preference,9
997,77-241-7621,26,Male,High,Married,Bachelor's,High,Warudoyong,Food & Beverages,$453.37,...,0,6,Desktop,Credit Card,3/11/2024,True,True,Wants-based,Express,9
998,53-091-2176,21,Female,High,Widowed,Bachelor's,Middle,Béziers,Baby Products,$106.15,...,0,5,Desktop,Cash,3/30/2024,True,True,Impulsive,Standard,8
999,48-203-9118,21,Female,Middle,Single,High School,High,Dongzhou,Health Care,$378.47,...,1,10,Tablet,Other,12/8/2024,False,False,Planned,Express,2

In [22]:
df2.duplicated() #yinelenen satırları bulma işlemi

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [24]:
df.isnull().any()

Customer_ID                              False
Age                                      False
Gender                                   False
Income_Level                             False
Marital_Status                           False
Education_Level                          False
Occupation                               False
Location                                 False
Purchase_Category                        False
Purchase_Amount                          False
Frequency_of_Purchase                    False
Purchase_Channel                         False
Brand_Loyalty                            False
Product_Rating                           False
Time_Spent_on_Product_Research(hours)    False
Social_Media_Influence                    True
Discount_Sensitivity                     False
Return_Rate                              False
Customer_Satisfaction                    False
Engagement_with_Ads                       True
Device_Used_for_Shopping                 False
Payment_Method                           False
Time_of_Purchase                         False
Discount_Used                            False
Customer_Loyalty_Program_Member          False
Purchase_Intent                          False
Shipping_Preference                      False
Time_to_Decision                         False
dtype: bool

In [25]:
df.isnull().sum()

Customer_ID                                0
Age                                        0
Gender                                     0
Income_Level                               0
Marital_Status                             0
Education_Level                            0
Occupation                                 0
Location                                   0
Purchase_Category                          0
Purchase_Amount                            0
Frequency_of_Purchase                      0
Purchase_Channel                           0
Brand_Loyalty                              0
Product_Rating                             0
Time_Spent_on_Product_Research(hours)      0
Social_Media_Influence                   247
Discount_Sensitivity                       0
Return_Rate                                0
Customer_Satisfaction                      0
Engagement_with_Ads                      256
Device_Used_for_Shopping                   0
Payment_Method                             0
Time_of_Purchase                           0
Discount_Used                              0
Customer_Loyalty_Program_Member            0
Purchase_Intent                            0
Shipping_Preference                        0
Time_to_Decision                           0
dtype: int64

In [27]:
df.fillna("değer yok") #boş değerleri doldurma işlemi

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
0,37-611-6911,22,Female,Middle,Married,Bachelor's,Middle,Évry,Gardening & Outdoors,$333.80,...,7,değer yok,Tablet,Credit Card,3/1/2024,True,False,Need-based,No Preference,2
1,29-392-9296,49,Male,High,Married,High School,High,Huocheng,Food & Beverages,$222.22,...,5,High,Tablet,PayPal,4/16/2024,True,False,Wants-based,Standard,6
2,84-649-5117,24,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,$426.22,...,7,Low,Smartphone,Debit Card,3/15/2024,True,True,Impulsive,No Preference,3
3,48-980-6078,29,Female,Middle,Single,Master's,Middle,Wiwilí,Home Appliances,$101.31,...,1,değer yok,Smartphone,Other,10/4/2024,True,True,Need-based,Express,10
4,91-170-9072,33,Female,Middle,Widowed,High School,Middle,Nara,Furniture,$211.70,...,10,değer yok,Smartphone,Debit Card,1/30/2024,False,False,Wants-based,No Preference,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,20-562-2569,44,Female,High,Divorced,Bachelor's,High,Aramayuan,Mobile Accessories,$463.67,...,4,değer yok,Tablet,PayPal,7/7/2024,True,False,Need-based,Standard,5
996,41-366-4205,50,Female,High,Single,High School,Middle,Paquera,Gardening & Outdoors,$69.78,...,6,Low,Tablet,Cash,3/28/2024,True,False,Wants-based,No Preference,9
997,77-241-7621,26,Male,High,Married,Bachelor's,High,Warudoyong,Food & Beverages,$453.37,...,6,High,Desktop,Credit Card,3/11/2024,True,True,Wants-based,Express,9
998,53-091-2176,21,Female,High,Widowed,Bachelor's,Middle,Béziers,Baby Products,$106.15,...,5,Medium,Desktop,Cash,3/30/2024,True,True,Impulsive,Standard,8
999,48-203-9118,21,Female,Middle,Single,High School,High,Dongzhou,Health Care,$378.47,...,10,Low,Tablet,Other,12/8/2024,False,False,Planned,Express,2

In [31]:
df.value_counts() #bir sütundaki benzersiz değerleri sayar

Customer_ID  Age  Gender  Income_Level  Marital_Status  Education_Level  Occupation  Location        Purchase_Category   Purchase_Amount  Frequency_of_Purchase  Purchase_Channel  Brand_Loyalty  Product_Rating  Time_Spent_on_Product_Research(hours)  Social_Media_Influence  Discount_Sensitivity  Return_Rate  Customer_Satisfaction  Engagement_with_Ads  Device_Used_for_Shopping  Payment_Method  Time_of_Purchase  Discount_Used  Customer_Loyalty_Program_Member  Purchase_Intent  Shipping_Preference  Time_to_Decision
00-149-4481  28   Female  High          Divorced        Master's         High        Kabale          Groceries           $464.76          2                      Mixed             5              1               0.0                                    Low                     Very Sensitive        0            3                      Low                  Desktop                   Debit Card      2/4/2024          False          True                             Need-based       No Preference        3                   1
68-296-5978  36   Male    High          Married         High School      Middle      Kadumelati      Hotels              $218.87          5                      Mixed             4              3               0.0                                    Medium                  Very Sensitive        0            4                      Medium               Smartphone                Cash            9/18/2024         True           False                            Planned          No Preference        11                  1
67-639-5838  23   Male    Middle        Married         High School      Middle      Shimorskoye     Packages)           $216.84          5                      In-Store          4              3               1.0                                    Low                     Somewhat Sensitive    1            1                      Low                  Tablet                    PayPal          3/28/2024         False          False                            Planned          Express              5                   1
67-676-5945  28   Female  High          Married         Bachelor's       High        Legaspi         Baby Products       $446.69          7                      In-Store          4              5               2.0                                    Medium                  Somewhat Sensitive    1            5                      High                 Smartphone                Cash            6/12/2024         False          True                             Planned          No Preference        13                  1
67-935-7964  41   Female  Middle        Single          High School      High        Nikolayevsk     Office Supplies     $205.49          4                      In-Store          5              3               2.0                                    Low                     Somewhat Sensitive    2            2                      High                 Tablet                    Cash            11/9/2024         True           False                            Need-based       Express              11                  1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ..
31-783-9785  19   Female  High          Divorced        Master's         Middle      Jambuwerkrajan  Toys & Games        $218.65          3                      Online            4              2               2.0                                    Low                     Very Sensitive        0            9                      Medium               Smartphone                Credit Card     7/17/2024         True           True                             Impulsive        Standard             4                   1
31-395-1286  47   Male    High          Married         High School      High        Ostashkov       Health Supplements  $197.12          10                     In-Store          4              4               0.0                                    Low                     Somewhat Sensitive    1            1                      Medium               Tablet                    Other           6/14/2024         True           True                             Wants-based      Standard             10                  1
31-284-5722  36   Female  High          Single          Bachelor's       High        Jianshan        Hotels              $351.71          7                      In-Store          2              2               0.0                                    Medium                  Very Sensitive        1            6                      Medium               Tablet                    Other           3/19/2024         True           False                            Need-based       Standard             8                   1
31-218-0024  21   Female  High          Divorced        High School      Middle      Lewotola        Health Supplements  $215.54          11                     Online            3              1               2.0                                    Low                     Somewhat Sensitive    2            6                      High                 Desktop                   Credit Card     4/8/2024          True           True                             Planned          No Preference        10                  1
99-945-7193  24   Female  Middle        Single          Master's         High        Lemery          Hotels              $254.29          9                      Mixed             5              4               0.0                                    Medium                  Somewhat Sensitive    1            7                      Low                  Smartphone                Cash            4/30/2024         False          False                            Impulsive        Express              3                   1
Name: count, Length: 564, dtype: int64

In [33]:
df.rename(columns={'Marital_Status': 'Is_Married'}) #sütunun adını değiştirme

,Customer_ID,Age,Gender,Income_Level,Is_Married,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
0,37-611-6911,22,Female,Middle,Married,Bachelor's,Middle,Évry,Gardening & Outdoors,$333.80,...,7,NaN,Tablet,Credit Card,3/1/2024,True,False,Need-based,No Preference,2
1,29-392-9296,49,Male,High,Married,High School,High,Huocheng,Food & Beverages,$222.22,...,5,High,Tablet,PayPal,4/16/2024,True,False,Wants-based,Standard,6
2,84-649-5117,24,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,$426.22,...,7,Low,Smartphone,Debit Card,3/15/2024,True,True,Impulsive,No Preference,3
3,48-980-6078,29,Female,Middle,Single,Master's,Middle,Wiwilí,Home Appliances,$101.31,...,1,NaN,Smartphone,Other,10/4/2024,True,True,Need-based,Express,10
4,91-170-9072,33,Female,Middle,Widowed,High School,Middle,Nara,Furniture,$211.70,...,10,NaN,Smartphone,Debit Card,1/30/2024,False,False,Wants-based,No Preference,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,20-562-2569,44,Female,High,Divorced,Bachelor's,High,Aramayuan,Mobile Accessories,$463.67,...,4,NaN,Tablet,PayPal,7/7/2024,True,False,Need-based,Standard,5
996,41-366-4205,50,Female,High,Single,High School,Middle,Paquera,Gardening & Outdoors,$69.78,...,6,Low,Tablet,Cash,3/28/2024,True,False,Wants-based,No Preference,9
997,77-241-7621,26,Male,High,Married,Bachelor's,High,Warudoyong,Food & Beverages,$453.37,...,6,High,Desktop,Credit Card,3/11/2024,True,True,Wants-based,Express,9
998,53-091-2176,21,Female,High,Widowed,Bachelor's,Middle,Béziers,Baby Products,$106.15,...,5,Medium,Desktop,Cash,3/30/2024,True,True,Impulsive,Standard,8
999,48-203-9118,21,Female,Middle,Single,High School,High,Dongzhou,Health Care,$378.47,...,10,Low,Tablet,Other,12/8/2024,False,False,Planned,Express,2

In [34]:
df.sort_values(by='Income_Level') #belirlenen sütuna göre sıralama yapma

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
665,68-458-0904,20,Female,High,Single,Bachelor's,High,Pyra,Sports & Outdoors,$131.90,...,4,Medium,Tablet,Credit Card,11/1/2024,True,True,Planned,No Preference,4
369,28-395-9872,38,Male,High,Married,Master's,Middle,Blantyre,Hotels,$65.68,...,8,Medium,Smartphone,Other,5/7/2024,False,False,Impulsive,Standard,12
368,90-322-7329,44,Female,High,Widowed,High School,Middle,Buensuseso,Luxury Goods,$312.93,...,7,NaN,Smartphone,PayPal,8/4/2024,True,True,Wants-based,No Preference,3
367,22-692-3470,46,Female,High,Widowed,High School,High,São Cristóvão,Sports & Outdoors,$159.45,...,5,NaN,Smartphone,Debit Card,6/14/2024,True,False,Impulsive,Standard,14
366,36-593-2907,42,Genderqueer,High,Single,Bachelor's,High,Karafao,Beauty & Personal Care,$157.21,...,3,High,Tablet,Debit Card,4/30/2024,True,False,Wants-based,Express,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,42-518-2602,30,Male,Middle,Divorced,Bachelor's,High,Navoiy,Home Appliances,$473.96,...,9,NaN,Tablet,PayPal,7/28/2024,True,False,Impulsive,Express,14
440,07-958-2231,27,Female,Middle,Married,Bachelor's,Middle,Tigaherang,Baby Products,$335.80,...,7,Low,Smartphone,Debit Card,2/10/2024,True,False,Wants-based,Standard,5
441,78-503-0416,25,Male,Middle,Single,High School,High,Villa Dolores,Luxury Goods,$85.57,...,4,Medium,Tablet,Debit Card,8/31/2024,True,True,Planned,No Preference,9
443,93-989-8649,26,Male,Middle,Divorced,Bachelor's,Middle,Shibushi,Food & Beverages,$172.50,...,8,Low,Desktop,Credit Card,7/19/2024,True,False,Impulsive,No Preference,7
999,48-203-9118,21,Female,Middle,Single,High School,High,Dongzhou,Health Care,$378.47,...,10,Low,Tablet,Other,12/8/2024,False,False,Planned,Express,2

In [37]:
df.replace({'Other': 'Cash'})	#bir değeri başka bir değerle değiştirme

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
0,37-611-6911,22,Female,Middle,Married,Bachelor's,Middle,Évry,Gardening & Outdoors,$333.80,...,7,NaN,Tablet,Credit Card,3/1/2024,True,False,Need-based,No Preference,2
1,29-392-9296,49,Male,High,Married,High School,High,Huocheng,Food & Beverages,$222.22,...,5,High,Tablet,PayPal,4/16/2024,True,False,Wants-based,Standard,6
2,84-649-5117,24,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,$426.22,...,7,Low,Smartphone,Debit Card,3/15/2024,True,True,Impulsive,No Preference,3
3,48-980-6078,29,Female,Middle,Single,Master's,Middle,Wiwilí,Home Appliances,$101.31,...,1,NaN,Smartphone,Cash,10/4/2024,True,True,Need-based,Express,10
4,91-170-9072,33,Female,Middle,Widowed,High School,Middle,Nara,Furniture,$211.70,...,10,NaN,Smartphone,Debit Card,1/30/2024,False,False,Wants-based,No Preference,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,20-562-2569,44,Female,High,Divorced,Bachelor's,High,Aramayuan,Mobile Accessories,$463.67,...,4,NaN,Tablet,PayPal,7/7/2024,True,False,Need-based,Standard,5
996,41-366-4205,50,Female,High,Single,High School,Middle,Paquera,Gardening & Outdoors,$69.78,...,6,Low,Tablet,Cash,3/28/2024,True,False,Wants-based,No Preference,9
997,77-241-7621,26,Male,High,Married,Bachelor's,High,Warudoyong,Food & Beverages,$453.37,...,6,High,Desktop,Credit Card,3/11/2024,True,True,Wants-based,Express,9
998,53-091-2176,21,Female,High,Widowed,Bachelor's,Middle,Béziers,Baby Products,$106.15,...,5,Medium,Desktop,Cash,3/30/2024,True,True,Impulsive,Standard,8
999,48-203-9118,21,Female,Middle,Single,High School,High,Dongzhou,Health Care,$378.47,...,10,Low,Tablet,Cash,12/8/2024,False,False,Planned,Express,2

In [46]:
df.dtypes  #sütun veri tiplerini gösterme işlemi

Customer_ID                               object
Age                                        int64
Gender                                    object
Income_Level                              object
Marital_Status                            object
Education_Level                           object
Occupation                                object
Location                                  object
Purchase_Category                         object
Purchase_Amount                           object
Frequency_of_Purchase                      int64
Purchase_Channel                          object
Brand_Loyalty                              int64
Product_Rating                             int64
Time_Spent_on_Product_Research(hours)    float64
Social_Media_Influence                    object
Discount_Sensitivity                      object
Return_Rate                                int64
Customer_Satisfaction                      int64
Engagement_with_Ads                       object
Device_Used_for_Shopping                  object
Payment_Method                            object
Time_of_Purchase                          object
Discount_Used                               bool
Customer_Loyalty_Program_Member             bool
Purchase_Intent                           object
Shipping_Preference                       object
Time_to_Decision                           int64
dtype: object

In [48]:
df.shape #satır ve sütun sayısını gösterme

(1000, 28)